services:
  - type: web
    name: senetrack
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: SECURE_SSL_REDIRECT
        value: "true"
      - key: USE_CLOUDINARY
        value: "true"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: MAPBOX_ACCESS_TOKEN
        sync: false
