"""
Django settings for root project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Redis URL for cache and sessions (set in production for concurrency)
REDIS_URL = os.environ.get('REDIS_URL', '').strip() or None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_DEFAULT_SECRET = 'django-insecure-nslt8yi9h@q!dqv(6%0g*j3zm(wad39#c@&l$$*^uzc#0l^vx@'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _DEFAULT_SECRET)

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for safety. Set DJANGO_DEBUG=True in .env for local development.
DEBUG = os.environ.get('DJANGO_DEBUG', 'false').lower() in ('true', '1', 'yes')

# Custom Admin Path (Security by Obscurity - avoids standard path bot scraping)
DJANGO_ADMIN_PATH = os.environ.get('DJANGO_ADMIN_PATH', 'manage-senetrack').strip('/')

# Require a non-default SECRET_KEY in production
if not DEBUG and SECRET_KEY == _DEFAULT_SECRET:
    raise ValueError(
        'Set DJANGO_SECRET_KEY in production. Do not use the default insecure key.'
    )

ALLOWED_HOSTS = [
    h.strip() 
    for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,senetrack-1073897174388.europe-west1.run.app,senetrack-1073897174388.us-east1.run.app,senetrack-1073897174388.us-central1.run.app').split(',') 
    if h.strip()
]
CSRF_TRUSTED_ORIGINS = [
    f"https://{h}" for h in ALLOWED_HOSTS if h not in ('localhost', '127.0.0.1')
]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'django.contrib.humanize',
    'scorecard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'root.middleware.ContentSecurityPolicyMiddleware',
]

ROOT_URLCONF = 'root.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'root.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# DATABASE_URL is only used in production (Cloud Run) or when USE_REMOTE_DB=true is set.
# Locally with DEBUG=True the app falls back to SQLite automatically.

_IS_CLOUD_RUN = os.environ.get('K_SERVICE') is not None
_use_remote_db = (
    _IS_CLOUD_RUN
    or not DEBUG
    or os.environ.get('USE_REMOTE_DB', 'false').lower() in ('true', '1', 'yes')
)

_db_config = dj_database_url.config(default=None, conn_max_age=60) if _use_remote_db else None
if _db_config:
    DATABASES = {'default': _db_config}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Caches (set REDIS_URL in production for shared cache and better concurrency)
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "scorecard" / "static",
]

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary settings
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    'PREFIX': '',
}

# Modern Django STORAGES configuration (Django 4.2+)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Use WhiteNoise for static files in production
if not DEBUG:
    STORAGES["staticfiles"] = {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
    # Don't fail if source maps or other referenced files are missing
    WHITENOISE_MANIFEST_STRICT = False

# Use Cloudinary for media storage on Cloud Run or when explicitly requested
if not DEBUG or _IS_CLOUD_RUN or os.environ.get('USE_CLOUDINARY', 'false').lower() == 'true':
    STORAGES["default"] = {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Mapbox access token for frontier map (get at https://account.mapbox.com/access-tokens/)
MAPBOX_ACCESS_TOKEN = os.environ.get('MAPBOX_ACCESS_TOKEN', 'pk.eyJ1IjoiZGVsdG8yNTQiLCJhIjoiY21taTNoeTl4MGFnMzJwczdoanZzdXhzcyJ9.VfdR2KBhUBPsLKGGl4Uusw')

# Kenya counties GeoJSON for frontier map (counties colored by region)
KENYA_COUNTIES_GEOJSON_URL = os.environ.get(
    'KENYA_COUNTIES_GEOJSON_URL',
    'https://raw.githubusercontent.com/abugasavio/ke.counties/master/counties.geojson'
)

# App-specific config (override via ACTIVE_DEBATES env var)
try:
    ACTIVE_DEBATES = int(os.environ.get('ACTIVE_DEBATES', 12))
except (TypeError, ValueError):
    ACTIVE_DEBATES = 12

LOGIN_REDIRECT_URL = '/admin/'

UNFOLD = {
    "SIDEBAR": {
        "show_search": False,
    },
}

# --- Security hardening ---
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # False so JS can read for AJAX if needed; set True if no JS CSRF usage

# --- Content Security Policy (CSP) ---
# Minimal CSP to protect against XSS. Allows images from Cloudinary/Mapbox and scripts from trusted sources.
# Note: If using inline scripts/styles, 'unsafe-inline' may be needed initially.
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://api.mapbox.com")
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://api.mapbox.com")
CSP_IMG_SRC = ("'self'", "data:", "https://res.cloudinary.com", "https://api.mapbox.com", "*.tiles.mapbox.com")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")
CSP_CONNECT_SRC = ("'self'", "https://api.mapbox.com", "https://events.mapbox.com")
CSP_FRAME_ANCESTORS = ("'none'",)

if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'true').lower() in ('true', '1', 'yes')
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
