# Generated by Django 5.2.11 on 2026-02-26 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senator_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('available_engines', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speeches', models.IntegerField(default=0)),
                ('attendance_rate', models.FloatField(default=0.0)),
                ('sponsored_bills', models.IntegerField(default=0)),
                ('passed_bills', models.IntegerField(default=0)),
                ('amendments', models.IntegerField(default=0)),
                ('committee_role', models.CharField(default='Member', max_length=100)),
                ('committee_attendance', models.FloatField(default=0.0)),
                ('total_votes', models.IntegerField(default=20)),
                ('attended_votes', models.IntegerField(default=0)),
                ('oversight_actions', models.IntegerField(default=0)),
                ('trend_data', models.JSONField(default=list)),
                ('senator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perf', to='scorecard.senator')),
            ],
        ),
    ]
