# Generated by Django 5.2.11 on 2026-02-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentaryperformance',
            name='county_representation_score',
            field=models.FloatField(default=0.0),
        ),
    ]
