# Generated by Django 6.0.2 on 2026-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_parliamentaryperformance_county_representation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo directly', null=True, upload_to='senators/'),
        ),
        migrations.AlterField(
            model_name='senator',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (used if no photo uploaded)', null=True),
        ),
    ]
