# Generated by Django 6.0.2 on 2026-02-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_senator_image_alter_senator_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='nomination',
            field=models.CharField(blank=True, help_text="For nominated senators, e.g. 'Women Affairs Interest'", max_length=150),
        ),
    ]
