# Generated by Django 6.0.2 on 2026-02-28 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0004_add_senator_nomination'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenatorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='The quote text (without surrounding quotes)')),
                ('date', models.DateField(help_text='Date the quote was said or published')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
                ('senator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='scorecard.senator')),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
    ]
