# Generated by Django 6.0.2 on 2026-03-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0005_add_senator_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='is_deceased',
            field=models.BooleanField(default=False, help_text='Mark if senator has passed on'),
        ),
    ]
