# Generated by Django 6.0.2 on 2026-03-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0006_add_senator_is_deceased'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('region', models.CharField(help_text='Region/frontier: coast, eastern, central, rift_valley, nyanza, western, north_eastern', max_length=50)),
                ('description', models.TextField(blank=True, help_text='County profile description (optional)')),
                ('logo', models.ImageField(blank=True, help_text='County logo/crest for the card', null=True, upload_to='counties/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['order', 'name'],
            },
        ),
    ]
