# Generated by Django 6.0.2 on 2026-03-02

from django.db import migrations


COUNTIES_DATA = [
    # Coast (order 1-6)
    ("Mombasa", "mombasa", "coast", 1),
    ("Kwale", "kwale", "coast", 2),
    ("Kilifi", "kilifi", "coast", 3),
    ("Tana River", "tana-river", "coast", 4),
    ("Lamu", "lamu", "coast", 5),
    ("Taita-Taveta", "taita-taveta", "coast", 6),
    # North Eastern (7-9)
    ("Garissa", "garissa", "north_eastern", 7),
    ("Wajir", "wajir", "north_eastern", 8),
    ("Mandera", "mandera", "north_eastern", 9),
    # Eastern (10-17)
    ("Marsabit", "marsabit", "eastern", 10),
    ("Isiolo", "isiolo", "eastern", 11),
    ("Meru", "meru", "eastern", 12),
    ("Tharaka-Nithi", "tharaka-nithi", "eastern", 13),
    ("Embu", "embu", "eastern", 14),
    ("Kitui", "kitui", "eastern", 15),
    ("Machakos", "machakos", "eastern", 16),
    ("Makueni", "makueni", "eastern", 17),
    # Central (18-23)
    ("Nyandarua", "nyandarua", "central", 18),
    ("Nyeri", "nyeri", "central", 19),
    ("Kirinyaga", "kirinyaga", "central", 20),
    ("Murang'a", "muranga", "central", 21),
    ("Kiambu", "kiambu", "central", 22),
    ("Nairobi", "nairobi", "central", 23),
    # Rift Valley (24-37)
    ("Turkana", "turkana", "rift_valley", 24),
    ("West Pokot", "west-pokot", "rift_valley", 25),
    ("Samburu", "samburu", "rift_valley", 26),
    ("Trans Nzoia", "trans-nzoia", "rift_valley", 27),
    ("Uasin Gishu", "uasin-gishu", "rift_valley", 28),
    ("Elgeyo-Marakwet", "elgeyo-marakwet", "rift_valley", 29),
    ("Nandi", "nandi", "rift_valley", 30),
    ("Baringo", "baringo", "rift_valley", 31),
    ("Laikipia", "laikipia", "rift_valley", 32),
    ("Nakuru", "nakuru", "rift_valley", 33),
    ("Narok", "narok", "rift_valley", 34),
    ("Kajiado", "kajiado", "rift_valley", 35),
    ("Kericho", "kericho", "rift_valley", 36),
    ("Bomet", "bomet", "rift_valley", 37),
    # Western (38-41)
    ("Kakamega", "kakamega", "western", 38),
    ("Vihiga", "vihiga", "western", 39),
    ("Bungoma", "bungoma", "western", 40),
    ("Busia", "busia", "western", 41),
    # Nyanza (42-47)
    ("Siaya", "siaya", "nyanza", 42),
    ("Kisumu", "kisumu", "nyanza", 43),
    ("Homa Bay", "homa-bay", "nyanza", 44),
    ("Migori", "migori", "nyanza", 45),
    ("Kisii", "kisii", "nyanza", 46),
    ("Nyamira", "nyamira", "nyanza", 47),
]


def populate_counties(apps, schema_editor):
    County = apps.get_model('scorecard', 'County')
    for name, slug, region, order in COUNTIES_DATA:
        County.objects.get_or_create(slug=slug, defaults={'name': name, 'region': region, 'order': order})


def reverse_populate(apps, schema_editor):
    County = apps.get_model('scorecard', 'County')
    County.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0007_add_county_model'),
    ]

    operations = [
        migrations.RunPython(populate_counties, reverse_populate),
    ]
