# Generated by Django 6.0.2 on 2026-03-02
# Populates county descriptions from research (Wikipedia, county gov sites)

from django.db import migrations


COUNTY_DESCRIPTIONS = {
    "mombasa": "Mombasa County is Kenya's smallest county by area (212.5 km²) and a major port city on the Indian Ocean. Capital Mombasa. Population ~1.2 million (2019). Key economic drivers: trade, tourism, shipping, and manufacturing. The county serves as a regional commercial hub with the Port of Mombasa.",
    "kwale": "Kwale County lies along the coast south of Mombasa, covering 8,270 km². Capital Kwale. Population ~867,000 (2019). Gateway county with proximity to Mombasa port and the Great Northern Corridor. Economy: tourism (Diani Beach), agriculture, mining (titanium), and trade.",
    "kilifi": "Kilifi County stretches along the coast north of Mombasa, 12,246 km². Capital Kilifi. Population ~1.45 million (2019). Known for Malindi and Watamu beach tourism, fishing, and coconut farming. Home to Kilifi Creek and diverse marine ecosystems.",
    "tana-river": "Tana River County is Kenya's fourth-largest by area (35,376 km²), traversed by the Tana River. Capital Hola. Population ~316,000 (2019). Semi-arid; economy based on pastoralism, irrigated agriculture along the Tana, and wildlife (Tana River Primate Reserve).",
    "lamu": "Lamu County includes the Lamu Archipelago on the northern coast. Area 6,498 km², population ~144,000 (2019). Capital Lamu Town, a UNESCO World Heritage site. Economy: tourism, fishing, and dhow building. Known for Swahili culture and historic architecture.",
    "taita-taveta": "Taita-Taveta County borders Tanzania, 17,084 km². Capital Mwatate. Population ~341,000 (2019). Home to Tsavo East and West National Parks. Economy: tourism, mining (gemstones), and agriculture. Taita Hills are a biodiversity hotspot.",
    "garissa": "Garissa County is in North Eastern Kenya, 45,720 km². Capital Garissa. Population ~841,000 (2019). Semi-arid; economy based on pastoralism and livestock. Key priorities: infrastructure, trade, and improving agricultural productivity.",
    "wajir": "Wajir County is Kenya's largest by area (55,841 km²). Capital Wajir. Population ~781,000 (2019). Arid; pastoral economy (camels, goats, sheep). Part of the former North Eastern Province.",
    "mandera": "Mandera County borders Ethiopia and Somalia, 25,798 km². Capital Mandera. Population ~867,000 (2019). Arid; pastoral economy. Strategic border location for cross-border trade.",
    "marsabit": "Marsabit County is Kenya's largest county by area (66,923 km²). Capital Marsabit. Population ~460,000 (2019). Includes Marsabit National Park and Lake Turkana. Economy: pastoralism, tourism, and small-scale agriculture.",
    "isiolo": "Isiolo County lies at the crossroads of northern Kenya, 25,336 km². Capital Isiolo. Population ~268,000 (2019). Gateway to northern parks; economy: pastoralism, tourism (Samburu, Buffalo Springs), and trade.",
    "meru": "Meru County is in the eastern highlands, 7,003 km². Capital Meru Town. Population ~1.55 million (2019). Fertile highlands; economy: coffee, tea, miraa, dairy, and horticulture. Home to Mount Kenya's eastern slopes.",
    "tharaka-nithi": "Tharaka-Nithi County was carved from Meru, 2,610 km². Capital Kathwana. Population ~393,000 (2019). Economy: agriculture (miraa, coffee, livestock) and small-scale trade.",
    "embu": "Embu County lies on the eastern slopes of Mount Kenya, 2,556 km². Capital Embu. Population ~609,000 (2019). Economy: coffee, tea, dairy, and horticulture. Fertile volcanic soils.",
    "kitui": "Kitui County is in eastern Kenya, 24,385 km². Capital Kitui. Population ~1.14 million (2019). Semi-arid; economy: livestock, drought-resistant crops, and mining (coal exploration).",
    "machakos": "Machakos County is near Nairobi, 5,953 km². Capital Machakos. Population ~1.42 million (2019). Growing satellite town; economy: agriculture, trade, and manufacturing. Part of the greater Nairobi metropolitan area.",
    "makueni": "Makueni County is in southeastern Kenya, 8,009 km². Capital Wote. Population ~988,000 (2019). Semi-arid; economy: livestock, drought-resistant crops, and bee-keeping. Tsavo East borders the county.",
    "nyandarua": "Nyandarua County is in the Central Highlands, 3,108 km². Capital Ol Kalou. Population ~638,000 (2019). Aberdare Range; economy: dairy, potatoes, pyrethrum, and tourism.",
    "nyeri": "Nyeri County lies on the southern slopes of Mount Kenya, 2,361 km². Capital Nyeri. Population ~759,000 (2019). Fertile; economy: coffee, tea, dairy, and horticulture. Home to Aberdare National Park.",
    "kirinyaga": "Kirinyaga County is on Mount Kenya's southeastern slopes, 1,205 km². Capital Kerugoya. Population ~610,000 (2019). Economy: rice (Mwea), coffee, tea, and horticulture. Mwea Irrigation Scheme is a major rice producer.",
    "muranga": "Murang'a County is in the Central Highlands, 2,326 km². Capital Murang'a. Population ~1.06 million (2019). Economy: coffee, tea, dairy, and horticulture. Birthplace of Kenya's independence movement.",
    "kiambu": "Kiambu County borders Nairobi to the north, 2,449 km². Capital Kiambu. Population ~2.42 million (2019). Part of Nairobi metro; economy: horticulture, dairy, coffee, and real estate.",
    "nairobi": "Nairobi is Kenya's capital and largest city, 695 km². Population ~4.4 million (2019). Economic powerhouse contributing ~27.5% of Kenya's GDP. Home to Parliament, UNEP, and Nairobi National Park—the only capital with a national park.",
    "turkana": "Turkana County is Kenya's largest by area (98,598 km²). Capital Lodwar. Population ~1.5 million (2019). Lake Turkana, oil exploration. Economy: pastoralism, fishing, and emerging oil sector.",
    "west-pokot": "West Pokot County borders Uganda, 8,418 km². Capital Kapenguria. Population ~621,000 (2019). Economy: livestock, agriculture, and mining. Known for the Pokot people and Cherangani Hills.",
    "samburu": "Samburu County is in the northern Rift Valley, 20,183 km². Capital Maralal. Population ~310,000 (2019). Economy: pastoralism and tourism (Samburu National Reserve). Home to the Samburu people.",
    "trans-nzoia": "Trans Nzoia County is in the Rift Valley, 2,470 km². Capital Kitale. Population ~990,000 (2019). 'Breadbasket of Kenya'; economy: maize, wheat, dairy, and horticulture.",
    "uasin-gishu": "Uasin Gishu County is in the Rift Valley, 2,955 km². Capital Eldoret. Population ~1.16 million (2019). Eldoret is a major hub; economy: agriculture, athletics (training camps), and trade.",
    "elgeyo-marakwet": "Elgeyo-Marakwet County is in the Rift Valley, 3,050 km². Capital Iten. Population ~454,000 (2019). 'Home of Champions'—world-famous for long-distance runners. Economy: athletics, agriculture, and tourism.",
    "nandi": "Nandi County is in the Rift Valley, 2,885 km². Capital Kapsabet. Population ~886,000 (2019). Birthplace of many Olympic champions. Economy: tea, maize, dairy, and athletics tourism.",
    "baringo": "Baringo County lies in the Rift Valley, 11,075 km². Capital Kabarnet. Population ~667,000 (2019). Lake Baringo and Lake Bogoria; economy: tourism, fishing, and pastoralism.",
    "laikipia": "Laikipia County is in the central Rift Valley, 8,696 km². Capital Rumuruti. Population ~519,000 (2019). Wildlife conservancies; economy: tourism, ranching, and conservation.",
    "nakuru": "Nakuru County is in the Rift Valley, 7,510 km². Capital Nakuru. Population ~2.16 million (2019). Lake Nakuru (flamingos), Menengai Crater. Economy: agriculture, tourism, and manufacturing.",
    "narok": "Narok County is in the Rift Valley, 17,921 km². Capital Narok. Population ~1.16 million (2019). Maasai Mara National Reserve; economy: tourism, livestock, and wheat farming.",
    "kajiado": "Kajiado County borders Tanzania, 21,293 km². Capital Kajiado. Population ~1.12 million (2019). Part of Nairobi metro; economy: livestock, mining (soda ash), and tourism (Amboseli).",
    "kericho": "Kericho County is in the South Rift, 2,455 km². Capital Kericho. Population ~902,000 (2019). Kenya's tea capital; major plantations. Economy: tea, forestry, and dairy.",
    "bomet": "Bomet County is in the South Rift, 1,998 km². Capital Bomet. Population ~876,000 (2019). Economy: tea, dairy, maize, and horticulture. Part of the tea-growing highlands.",
    "kakamega": "Kakamega County is in Western Kenya, 3,034 km². Capital Kakamega. Population ~1.87 million (2019). Kakamega Forest—Kenya's only tropical rainforest. Economy: agriculture, forestry, and trade.",
    "vihiga": "Vihiga County is Kenya's smallest by area (531 km²). Capital Mbale. Population ~590,000 (2019). Densely populated; economy: tea, sugarcane, and subsistence farming.",
    "bungoma": "Bungoma County is in Western Kenya, 2,207 km². Capital Bungoma. Population ~1.67 million (2019). Economy: sugarcane, maize, and dairy. Nzoia Sugar Company is a major employer.",
    "busia": "Busia County borders Uganda, 1,628 km². Capital Busia. Population ~894,000 (2019). Border town; economy: cross-border trade, agriculture, and fishing (Lake Victoria).",
    "siaya": "Siaya County is in Nyanza, 2,496 km². Capital Siaya. Population ~993,000 (2019). Birthplace of Oginga Odinga. Economy: fishing, rice, sugarcane, and trade.",
    "kisumu": "Kisumu County is on Lake Victoria, 2,010 km². Capital Kisumu. Population ~1.16 million (2019). Kenya's third-largest city; economy: fishing, trade, sugarcane, and services. Luo cultural center.",
    "homa-bay": "Homa Bay County is on Lake Victoria, 3,155 km². Capital Homa Bay. Population ~1.13 million (2019). Economy: fishing, rice farming, and sugarcane. Ruma National Park.",
    "migori": "Migori County borders Tanzania, 2,586 km². Capital Migori. Population ~1.12 million (2019). Economy: gold mining, sugarcane, fishing, and trade. Macalder gold mines.",
    "kisii": "Kisii County is in the highlands of Nyanza, 1,318 km². Capital Kisii. Population ~1.27 million (2019). Densely populated; economy: tea, bananas, soapstone carving, and trade.",
    "nyamira": "Nyamira County was carved from Kisii, 913 km². Capital Nyamira. Population ~606,000 (2019). Economy: tea, pyrethrum, and dairy. Part of the Gusii highlands.",
}


def populate_descriptions(apps, schema_editor):
    County = apps.get_model('scorecard', 'County')
    for slug, description in COUNTY_DESCRIPTIONS.items():
        County.objects.filter(slug=slug).update(description=description)


def reverse_populate(apps, schema_editor):
    County = apps.get_model('scorecard', 'County')
    County.objects.all().update(description='')


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0009_add_county_image'),
    ]

    operations = [
        migrations.RunPython(populate_descriptions, reverse_populate),
    ]
