# Generated by Django 6.0.2 on 2026-03-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0013_remove_legacy_county_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='governor_image',
            field=models.ImageField(blank=True, help_text="Governor's photo", null=True, upload_to='counties/governors/'),
        ),
        migrations.AddField(
            model_name='county',
            name='governor_name',
            field=models.CharField(blank=True, help_text="County governor's name", max_length=150),
        ),
    ]
