# Generated by Django 6.0.2 on 2026-03-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0014_add_governor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='official_profile_url',
            field=models.URLField(blank=True, help_text='Link to official county government profile (e.g. county website)'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('scorecard', 'County').objects.filter(
                name__iexact='Tharaka-Nithi'
            ).update(official_profile_url='https://tharakanithi.go.ke/county-profile/'),
            migrations.RunPython.noop,
        ),
    ]
