# Generated by Django 6.0.2 on 2026-03-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0015_add_official_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='development_dashboard_url',
            field=models.URLField(blank=True, help_text='Link to county development/project dashboard (e.g. PTMMS)'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('scorecard', 'County').objects.filter(
                name__iexact='Lamu'
            ).update(development_dashboard_url='https://ptmms.lamu.go.ke/'),
            migrations.RunPython.noop,
        ),
    ]
