# Generated by Django 6.0.2 on 2026-03-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0016_add_development_dashboard_url'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('scorecard', 'County').objects.filter(
                name__iexact='Makueni'
            ).update(development_dashboard_url='https://pmts.makueni.go.ke/views/'),
            migrations.RunPython.noop,
        ),
    ]
