# Generated by Django 6.0.2 on 2026-03-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0017_add_makueni_dashboard_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='women_rep_image',
            field=models.ImageField(blank=True, help_text="Women representative's photo", null=True, upload_to='counties/women_rep/'),
        ),
        migrations.AddField(
            model_name='county',
            name='women_rep_name',
            field=models.CharField(blank=True, help_text="County women representative's name", max_length=150),
        ),
    ]
