# Generated by Django 6.0.2 on 2026-03-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0018_add_women_rep_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='governor_party',
            field=models.CharField(blank=True, help_text="Governor's political party", max_length=100),
        ),
        migrations.AddField(
            model_name='county',
            name='women_rep_party',
            field=models.CharField(blank=True, help_text="Women representative's political party", max_length=100),
        ),
    ]
