# Generated by Django

from django.db import migrations


def normalize_regions(apps, schema_editor):
    """Normalize County.region to lowercase to fix duplicates (e.g. Western vs western)."""
    County = apps.get_model("scorecard", "County")
    mapping = {
        "Coast": "coast",
        "Western": "western",
        "Eastern": "eastern",
        "Central": "central",
        "National": "national",
    }
    for county in County.objects.all():
        new_region = mapping.get(county.region)
        if new_region:
            county.region = new_region
            county.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scorecard", "0019_add_governor_women_rep_party"),
    ]

    operations = [
        migrations.RunPython(normalize_regions, noop),
    ]
