# Generated by Django 6.0.2 on 2026-03-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0020_normalize_county_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentaryperformance',
            name='debate_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parliamentaryperformance',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='parliamentaryperformance',
            name='motions_sponsored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parliamentaryperformance',
            name='overall_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parliamentaryperformance',
            name='sessions_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parliamentaryperformance',
            name='structural_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parliamentaryperformance',
            name='words_spoken',
            field=models.IntegerField(default=0),
        ),
    ]
