# Generated by Django 6.0.2 on 2026-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0021_add_hansard_performance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exact name as used on senators (e.g. United Democratic Alliance)', max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Party logo for senator cards', null=True, upload_to='parties/')),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
            },
        ),
    ]
