# Generated by Django 6.0.2 on 2026-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0022_add_party_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentaryperformance',
            name='statements_2025',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parliamentaryperformance',
            name='statements_total',
            field=models.IntegerField(default=0),
        ),
    ]
