# Generated by Django 6.0.2 on 2026-03-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0023_add_statements_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the party was founded (e.g. 2000)', null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='leader_name',
            field=models.CharField(blank=True, help_text='Current national party leader', max_length=150),
        ),
    ]
