# Generated by Django 6.0.2 on 2026-03-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0024_party_founded_year_party_leader_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='history',
            field=models.TextField(blank=True, help_text='Short history/description to show in party info card'),
        ),
    ]
