# Generated by Django 6.0.2 on 2026-03-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0025_party_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='is_still_computing',
            field=models.BooleanField(default=False, help_text='Mark if this senator is newly added and performance data is still being computed.'),
        ),
    ]
