# Generated by Django 6.0.2 on 2026-03-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0026_senator_is_still_computing'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the vote as recorded in the Hansard/division list')),
                ('title', models.CharField(help_text='Short description of the motion, bill, or question', max_length=255)),
                ('decision', models.CharField(help_text='Recorded position, e.g. Yes, No, Abstain, Absent', max_length=20)),
                ('source', models.URLField(blank=True, help_text='Optional link to the official record (Hansard, Mzalendo, Parliament portal)')),
                ('senator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_records', to='scorecard.senator')),
            ],
            options={
                'ordering': ['-date', 'senator__name'],
            },
        ),
    ]
