# Generated by Django 6.0.2 on 2026-03-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0027_votingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='is_no_longer_serving',
            field=models.BooleanField(default=False, help_text='Mark if this senator is no longer serving in the Senate (e.g. expelled, resigned).'),
        ),
    ]
