# Generated by Django 6.0.2 on 2026-03-25 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0029_add_missing_parties'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('data_error', 'Data Error'), ('methodology', 'Methodology Challenge'), ('general', 'General Feedback'), ('media', 'Media Enquiry'), ('other', 'Other')], db_index=True, default='general', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('organisation', models.CharField(blank=True, help_text='Organisation / affiliation (optional)', max_length=150)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not shown to sender)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('senator_ref', models.ForeignKey(blank=True, help_text='Senator this message relates to (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='scorecard.senator')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
